### ISSUE TITLE
unresolved dependency

### ISSUE THREAD

**Issue by nku-ting** [leesf/summingbird-hybrid-example-china#1]
我搭了zookeeper，memcached，kafka，然后都成功启动，在运行sbt compile的时候出错：
unresolved dependency：org.scala-lang#scala-library;2.10.3:not found
unresolved dependency：log4j#log4j;1.2.16:not found
unresolved dependency：com.twitter#summingbird-core_2.10;0.4.1:notfound
......
该怎么解决呢？我是不是需要安Scala？
![summing](https://cloud.githubusercontent.com/assets/18554224/14641916/f73a911a-067a-11e6-97b7-752bfe5418d0.PNG)

**Comment by leesf** [comment]
是的，是需要配置scala环境的

**Comment by nku-ting** [comment]
我又配置了Scala，也装了Scala的插件idea-IC，结果还是上面的错误，现在我的虚拟机里装的有hadoop，storm，zookeeper，kafka，memcached，Scala，依然有那么多的not found，总觉得我是少装了什么东西，求指教。。

**Comment by leesf** [comment]
笔者的机器环境为ubuntu，配置了zookeeper、kafka、memcached、scala。就只有这些，您上面的是缺少了依赖包，但是在sbt中已经添加了这些依赖。

**Comment by nku-ting** [comment]
我修改了build.sbt如下：
resolvers ++= Seq(
  Opts.resolver.sonatypeSnapshots,
  Opts.resolver.sonatypeReleases,
  "maven Rpository" at "http://maven.apache.org",
  "Clojars Repository" at "http://clojars.org/repo",
  "Conjars Repository" at "http://conjars.org/repo",
  "oss Repository" at "http://maven.apache.org",
  "Twitter Maven" at "http://maven.twttr.com",
  "Twitter Maven Repo" at "http://maven.twttr.com" 
)
上面的依赖问题解决了，编译成功，但是在sbt run的时候，又出现了问题，不知道您当初遇到过没，有没有什么方法可以解决。十分感谢

[error](run-main-0) java.lang.ClassNotFoundException: scala.Function0
java.lang.ClassNotFoundException: scala.Function0
[trace] Stack trace suppressed: run last summingbird-example/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last summingbird-example/compile:run for the full output.
[error](summingbird-example/compile:run) Nonzero exit code: 1

**Comment by leesf** [comment]
不好意思，才看到，当初配置好依赖后，就可以运行了。没有遇到您贴出来的问题

**Comment by nku-ting** [comment]
我运行您的demo，在run的时候进行选择，选择2 ExeStorm,会报错“Must submit topologies using the 'storm' client script so that StormSubmitter knows which jar to upload”，选择4 RunHybrid会一直报拒绝连接的错误。现在比较困惑的是，这个demo实现的功能是什么呢？您当初写这个demo的时候，参照了什么summingbird编程接口呢？我想一边学习summingbird编程接口一边解决demo不能运行的问题，但是网上我能找到的summingbird的资料好少，您当初的资料还在吗或者有什么学习资源可以分享吗？谢谢~

**Comment by leesf** [comment]
这个demo是我参考的其他的demo（可以在github上搜索到，但是依赖库无法访问）修改的。这个demo主要实现的功能如下：一个线程不断的随机生成数字消息，然后这些消息会进入kafka消息队列，kafka消息队列的消息分别到达在线层进行在线计算和存入本地，存入本地的数据在一个批次到达后就开始进行批量计算；并且会不断的进行查询某个数字出现的次数。https://groups.google.com/forum/#!forum/summingbird，这是一个论坛，您可以看看。

**Comment by nku-ting** [comment]
请问您的demo用的zookeeper、kafka、memcached、Scala都是什么版本的呢？

**Comment by leesf** [comment]
zookeeper 3.4.6
kafka 2.11-0.8.2.1
memcached 1.4.24
scala 2.11.7

------------------ 原始邮件 ------------------
发件人: "nku-ting";notifications@github.com;
发送时间: 2016年7月11日(星期一) 上午8:53
收件人: "leesf/summingbird-hybrid-example-china"summingbird-hybrid-example-china@noreply.github.com; 
抄送: "Leesf"490081539@qq.com; "Comment"comment@noreply.github.com; 
主题: Re: [leesf/summingbird-hybrid-example-china] unresolved dependency(#1)

请问您的demo用的zookeeper、kafka、memcached、Scala都是什么版本的呢？

**Comment by nku-ting** [comment]
我重搭环境之后，运行demo，得到了跟您形式一样的结果，只是结果全都为0，中间还有提示，no broker partitions consumed by consumer thread **\* for topic **,我查到这是kafka的错误，看了kafka的原理，kafkaspout的代码，但是依然没有找到问题在哪儿要如何修改，您有什么想法吗？谢谢。

运行结果：
180592 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - Sanity Check
180592 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - lookupDebug(7)
180610 [pool-3-thread-1] INFO  summingbird.proto.HybridRunner$ - Offline: None
180612 [pool-3-thread-1] INFO  summingbird.proto.HybridRunner$ - Online: (BatchID.4894857,None)
180616 [pool-3-thread-1] INFO  summingbird.proto.HybridRunner$ - Hybrid: None
180616 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - Events Produced: 0
180616 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - Events Ingested: 0
180626 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - Events Counted (offline): 0
180629 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - Events Counted (online): 0
180661 [pool-3-thread-1] INFO  summingbird.proto.RunHybrid$ - Events Counted (hybrid): 0

中间提示：
16/07/14 08:45:26 WARN consumer.ZookeeperConsumerConnector: [summingbird-prototype-storm_master-1468457124853-57398e35], No broker partitions consumed by consumer thread summingbird-prototype-storm_master-1468457124853-57398e35-0 for topic summingbird.proto.productview
