### ISSUE TITLE
demo实现的是什么功能？

### ISSUE THREAD

**Issue by nku-ting** [leesf/summingbird-hybrid-example-china#2]
经过一番努力，终于把demo跑起来了，也得到了与您形式一致的结果，但是这些是什么结果呢？这个demo实现的功能是什么啊？
我开始理解的是lookupDebug(*)就是统计 \* 出现的次数，但是用一些数据测试了一下，发现好像不对，请问是我理解错了吗？

**Comment by leesf** [comment]
您好，这个demo实现的功能就是统计某个数字出现的次数。
